### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by havardox** [martin-honnen/SaxonHE12s9apiExtensions#1]
How do I apply a XSLT transformation from the command line?

**Comment by martin-honnen** [comment]
If you are looking for a command line .NET tool to use Saxon HE 12 then see https://www.nuget.org/packages/SaxonHE12NetXslt/.

If you want to write your own code using this package then see https://www.nuget.org/packages/SaxonHE12s9apiExtensions/#readme-body-tab, it has the example
```
using net.sf.saxon.s9api;
using net.liberty_development.SaxonHE12s9apiExtensions;

var processor = new Processor(false);

Console.WriteLine($"{processor.getSaxonEdition()} {processor.getSaxonProductVersion()}");

var xslt30Transformer = processor.newXsltCompiler().Compile(new Uri("https://github.com/martin-honnen/martin-honnen.github.io/raw/master/xslt/processorTestHTML5Xslt3InitialTempl.xsl")).load30();

xslt30Transformer.callTemplate(null, processor.NewSerializer(Console.Out));
```

**Comment by martin-honnen** [comment]
There is also an adaption of the Saxonica SaxonCS sample methods to this Saxon HE 12 Java to .NET cross-compilation at https://github.com/martin-honnen/SaxonHE12IKVMNet6SaxonCSSamplesAdapted which shows lots of different use cases for XSLT 3, XQuery 3.1 and XPath 3.1.

**Comment by martin-honnen** [comment]
I have also updated the minimal console app project https://github.com/martin-honnen/SaxonHE12IKVMExampleConsoleApp to use the latest version of Saxon 12.5 by using the latest/current version of this package.

**Comment by martin-honnen** [comment]
@havardox , do the responses help?

**Comment by havardox** [comment]
Thanks for replying. Regarding this specific example:

```
using net.sf.saxon.s9api;
using net.liberty_development.SaxonHE12s9apiExtensions;

var processor = new Processor(false);

Console.WriteLine($"{processor.getSaxonEdition()} {processor.getSaxonProductVersion()}");

var xslt30Transformer = processor.newXsltCompiler().Compile(new Uri("https://github.com/martin-honnen/martin-honnen.github.io/raw/master/xslt/processorTestHTML5Xslt3InitialTempl.xsl")).load30();

xslt30Transformer.callTemplate(null, processor.NewSerializer(Console.Out));
```

Where in the code would I load an external XML file to apply the XSLT transformation to?

**Comment by martin-honnen** [comment]
Well, in XSLT 3 https://www.w3.org/TR/xslt-30/#initiating there are different ways to run XSLT, one, to call a named template, is shown in that example.

If you want to apply templates to an input document (node), you better use a different method than `callTemplate`, remember, that is the Saxon https://www.saxonica.com/html/documentation12/using-xsl/embedding/s9api-transformation.html API of Xslt30Transformer https://www.saxonica.com/html/documentation12/javadoc/net/sf/saxon/s9api/Xslt30Transformer.html, it literally has a method `applyTemplates`, one overload is https://www.saxonica.com/html/documentation12/javadoc/net/sf/saxon/s9api/Xslt30Transformer.html#applyTemplates(javax.xml.transform.Source,net.sf.saxon.s9api.Destination), and it literally has a method `transform` https://www.saxonica.com/html/documentation12/javadoc/net/sf/saxon/s9api/Xslt30Transformer.html#transform(javax.xml.transform.Source,net.sf.saxon.s9api.Destination).

So look at https://github.com/martin-honnen/SaxonHE12IKVMNet6SaxonCSSamplesAdapted/blob/master/SaxonHE12Examples.cs#L478 doing e.g.
```
        // Create a Processor instance.
        Processor processor = new(false);

        // Load the source document
        XdmNode input = processor.newDocumentBuilder().Build(new Uri(samplesDir, "data/books.xml"));

        // Create a transformer for the stylesheet.
        Xslt30Transformer transformer = processor.newXsltCompiler().Compile(new Uri(samplesDir, "styles/books.xsl")).load30();

        // Set the root node of the source document to be the global context item
        transformer.setGlobalContextItem(input);

        // Create a serializer, with output to the standard output stream
        Serializer serializer = processor.NewSerializer(Console.Out);
        //serializer.setOutputStream(java.lang.System.@out);

        // Transform the source XML and serialize the result document
        transformer.applyTemplates(input, serializer);
```

**Comment by martin-honnen** [comment]
@havardox , have you got it working?

**Comment by martin-honnen** [comment]
I assume this issue is resolved as you haven't answered in the last three days.
